### ISSUE TITLE
feat: Implement Header and Navigation bar

### ISSUE THREAD

**Issue by chulheungkim** [Hongik-Industrial-Design/HID_Web_FE#3]
상단의 메인 로고와 내비게이션 바(검색 버튼 포함)를 포함한 헤더 영역을 구현합니다.
반응형 디자인과 드롭다운 메뉴, 검색 기능 등의 상호작용 요소도 포함합니다.

### Tasks

- [x] 내비게이션 바, 로고를 포함한 헤더 레이아웃 생성
- [x] 내비게이션 항목에 Dropdown 메뉴 구현
- [ ] 헤더가 다양한 화면 크기에 적응할 수 있도록 반응형 디자인 추가
- [ ] 내비게이션 바에 검색 기능을 통합
- [ ] 헤더를 다양한 브라우저와 기기에서 테스트
