### ISSUE TITLE
feat: Implement Category Navigation

### ISSUE THREAD

**Issue by chulheungkim** [Hongik-Industrial-Design/HID_Web_FE#5]
### Tasks

- [x] "All", "Smart Mobility", "Spatial" 등의 카테고리 네비게이션 버튼을 생성
- [ ] 선택된 카테고리에 따라 콘텐츠를 필터링하는 logic 구현
- [ ] 필터 및 카테고리 네비게이션에 대한 반응형 구현
- [x] 버튼에 적절한 hover 및 click 효과 적용
- [ ] 필터링 기능을 다양한 기기와 브라우저에서 테스트

### Issue Dependency
This issue depends on #6
