### ISSUE TITLE
feat: Implement Portfolio Grid Layout

### ISSUE THREAD

**Issue by chulheungkim** [Hongik-Industrial-Design/HID_Web_FE#6]
### Tasks

- [ ] 포트폴리오 항목을 보여줄 그리드 레이아웃 디자인 및 구현
- [ ] 포트폴리오 항목에 확대 또는 텍스트 오버레이와 같은 hover 효과를 추가
- [ ] 각 항목이 클릭 시 상세 페이지로 연결되도록 라우팅 구현
- [ ] 그리드 레이아웃이 다양한 화면 크기에 맞게 반응형 구현
- [ ] 그리드 레이아웃을 다양한 기기와 브라우저에서 테스트

### Issue Dependency
This issue depends on #5
