### ISSUE TITLE
feat: Implement Footer

### ISSUE THREAD

**Issue by chulheungkim** [Hongik-Industrial-Design/HID_Web_FE#7]
로고, 주소, 연락처 정보, 소셜 미디어 링크 등을 포함한 푸터 영역을 디자인하고 구현합니다.
푸터가 전체 디자인과 일관성을 유지하며, 반응형으로 동작하도록 합니다.

### Tasks

- [ ] 로고, 주소, 연락처 정보를 포함한 푸터 레이아웃 디자인
- [ ] 적절한 아이콘과 함께 소셜 미디어 링크 추가
- [ ] 푸터의 반응형 디자인 구현
- [ ] 푸터를 다양한 기기와 브라우저에서 테스트
